//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ccen.Model.USHolidayService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.27seconds.com/Holidays/US/", ConfigurationName="USHolidayService.USHolidayServiceSoap")]
    public interface USHolidayServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.27seconds.com/Holidays/US/GetHolidaysAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHolidaysAvailable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.27seconds.com/Holidays/US/GetHolidayDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetHolidayDate(string holidayName, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.27seconds.com/Holidays/US/GetHolidaysForDateRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHolidaysForDateRange(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.27seconds.com/Holidays/US/GetHolidaysForMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHolidaysForMonth(int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.27seconds.com/Holidays/US/GetHolidaysForYear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHolidaysForYear(int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USHolidayServiceSoapChannel : Ccen.Model.USHolidayService.USHolidayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USHolidayServiceSoapClient : System.ServiceModel.ClientBase<Ccen.Model.USHolidayService.USHolidayServiceSoap>, Ccen.Model.USHolidayService.USHolidayServiceSoap {
        
        public USHolidayServiceSoapClient() {
        }
        
        public USHolidayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USHolidayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USHolidayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USHolidayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetHolidaysAvailable() {
            return base.Channel.GetHolidaysAvailable();
        }
        
        public System.DateTime GetHolidayDate(string holidayName, int year) {
            return base.Channel.GetHolidayDate(holidayName, year);
        }
        
        public System.Data.DataSet GetHolidaysForDateRange(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetHolidaysForDateRange(startDate, endDate);
        }
        
        public System.Data.DataSet GetHolidaysForMonth(int year, int month) {
            return base.Channel.GetHolidaysForMonth(year, month);
        }
        
        public System.Data.DataSet GetHolidaysForYear(int year) {
            return base.Channel.GetHolidaysForYear(year);
        }
    }
}
