using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Amazon.DTO;
using Amazon.DTO.Inventory;
using Amazon.Web.Models.Exports;

namespace Amazon.Web.ViewModels.Products
{
    public class ItemVariationExportViewModel
    {
        public int? Id { get; set; }

        public string StyleString { get; set; }
        public long? StyleId { get; set; }
        public long? StyleItemId { get; set; }
        public string StyleSize { get; set; }
        public string StyleColor { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
        public string SKU { get; set; }

        public string BrandName { get; set; }

        public string Barcode { get; set; }
        public bool AutoGeneratedBarcode { get; set; }

        public int AutoGeneratedBarcodeInt
        {
            get { return AutoGeneratedBarcode ? 1 : 0; }
            set { AutoGeneratedBarcode = value == 0 ? false : true; }
        }

        public int RealQuantity { get; set; }
        
        public bool IsFBA { get; set; }
        public bool IsPrime { get; set; }

        public bool IsSelected { get; set; }

        public ItemVariationExportViewModel()
        {
            
        }


        public ItemVariationExportViewModel(ItemDTO item)
        {
            Id = item.Id;

            StyleString = item.StyleString;
            StyleId = item.StyleId;
            StyleItemId = item.StyleItemId;
            StyleSize = item.StyleSize;
            StyleColor = item.StyleColor;

            Size = item.Size;
            Color = item.Color;

            Barcode = item.Barcode;

            Price = item.CurrentPrice;
            SKU = item.SKU;

            BrandName = item.BrandName;

            IsPrime = item.IsPrime;
            IsFBA = item.IsFBA;

            RealQuantity = item.RealQuantity;
            IsSelected = true;
        }
    }
}