
namespace Amazon.Core.Entities
{
    public enum AmazonReportType
    {
        _GET_MERCHANT_LISTINGS_DATA_,
        _GET_ORDERS_DATA_,
        _GET_MERCHANT_LISTINGS_DATA_LITE_,
        //_GET_FLAT_FILE_ORDERS_DATA_
        _GET_MERCHANT_CATEGORY_LISTINGS_DATE_,

        _GET_AMAZON_FULFILLED_SHIPMENTS_DATA_,

        _GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA_,

        _GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2_,

        _GET_AFN_INVENTORY_DATA_,

        _GET_FLAT_FILE_OPEN_LISTINGS_DATA_,

        //TEMP
        //_GET_PAYMENT_SETTLEMENT_DATA_
        _GET_MERCHANT_LISTINGS_DEFECT_DATA_,

        _GET_XML_RETURNS_DATA_BY_RETURN_DATE_,
    }
}
