// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Amazon.Web.Controllers
{
    public partial class EmailController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmailController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EmailController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllEmails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllEmails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadAttachment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AttachStyleImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachStyleImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Validate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Validate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendEmail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ComposeEmailFromTemplate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComposeEmailFromTemplate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetTemplateInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTemplateInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReplyTo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReplyTo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ComposeEmail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComposeEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetNoResponseNeeded()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetNoResponseNeeded);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DismissResponsePromised()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DismissResponsePromised);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MarkAsReviewed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkAsReviewed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewEmail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAttachment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAttachment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AssignEmailToOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssignEmailToOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Escalate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Escalate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmailController Actions { get { return MVC.Email; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Email";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Email";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetAllEmails = "GetAllEmails";
            public readonly string UploadAttachment = "UploadAttachment";
            public readonly string AttachStyleImage = "AttachStyleImage";
            public readonly string Validate = "Validate";
            public readonly string SendEmail = "SendEmail";
            public readonly string TestEmail = "TestEmail";
            public readonly string ComposeEmailFromTemplate = "ComposeEmailFromTemplate";
            public readonly string GetTemplateInfo = "GetTemplateInfo";
            public readonly string ReplyTo = "ReplyTo";
            public readonly string ComposeEmail = "ComposeEmail";
            public readonly string SetNoResponseNeeded = "SetNoResponseNeeded";
            public readonly string DismissResponsePromised = "DismissResponsePromised";
            public readonly string MarkAsReviewed = "MarkAsReviewed";
            public readonly string ViewEmail = "ViewEmail";
            public readonly string GetAttachment = "GetAttachment";
            public readonly string AssignEmailToOrder = "AssignEmailToOrder";
            public readonly string Escalate = "Escalate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetAllEmails = "GetAllEmails";
            public const string UploadAttachment = "UploadAttachment";
            public const string AttachStyleImage = "AttachStyleImage";
            public const string Validate = "Validate";
            public const string SendEmail = "SendEmail";
            public const string TestEmail = "TestEmail";
            public const string ComposeEmailFromTemplate = "ComposeEmailFromTemplate";
            public const string GetTemplateInfo = "GetTemplateInfo";
            public const string ReplyTo = "ReplyTo";
            public const string ComposeEmail = "ComposeEmail";
            public const string SetNoResponseNeeded = "SetNoResponseNeeded";
            public const string DismissResponsePromised = "DismissResponsePromised";
            public const string MarkAsReviewed = "MarkAsReviewed";
            public const string ViewEmail = "ViewEmail";
            public const string GetAttachment = "GetAttachment";
            public const string AssignEmailToOrder = "AssignEmailToOrder";
            public const string Escalate = "Escalate";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string orderId = "orderId";
        }
        static readonly ActionParamsClass_GetAllEmails s_params_GetAllEmails = new ActionParamsClass_GetAllEmails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllEmails GetAllEmailsParams { get { return s_params_GetAllEmails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllEmails
        {
            public readonly string request = "request";
            public readonly string dateFrom = "dateFrom";
            public readonly string dateTo = "dateTo";
            public readonly string buyerName = "buyerName";
            public readonly string orderNumber = "orderNumber";
            public readonly string market = "market";
            public readonly string onlyIncoming = "onlyIncoming";
            public readonly string onlyWithoutAnswer = "onlyWithoutAnswer";
            public readonly string includeSystem = "includeSystem";
            public readonly string responseStatus = "responseStatus";
        }
        static readonly ActionParamsClass_UploadAttachment s_params_UploadAttachment = new ActionParamsClass_UploadAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadAttachment UploadAttachmentParams { get { return s_params_UploadAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadAttachment
        {
            public readonly string request = "request";
            public readonly string files = "files";
        }
        static readonly ActionParamsClass_AttachStyleImage s_params_AttachStyleImage = new ActionParamsClass_AttachStyleImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AttachStyleImage AttachStyleImageParams { get { return s_params_AttachStyleImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AttachStyleImage
        {
            public readonly string styleId = "styleId";
        }
        static readonly ActionParamsClass_Validate s_params_Validate = new ActionParamsClass_Validate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Validate ValidateParams { get { return s_params_Validate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Validate
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SendEmail s_params_SendEmail = new ActionParamsClass_SendEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendEmail SendEmailParams { get { return s_params_SendEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendEmail
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ComposeEmailFromTemplate s_params_ComposeEmailFromTemplate = new ActionParamsClass_ComposeEmailFromTemplate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ComposeEmailFromTemplate ComposeEmailFromTemplateParams { get { return s_params_ComposeEmailFromTemplate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ComposeEmailFromTemplate
        {
            public readonly string orderNumber = "orderNumber";
            public readonly string type = "type";
            public readonly string replyToId = "replyToId";
        }
        static readonly ActionParamsClass_GetTemplateInfo s_params_GetTemplateInfo = new ActionParamsClass_GetTemplateInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTemplateInfo GetTemplateInfoParams { get { return s_params_GetTemplateInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTemplateInfo
        {
            public readonly string orderNumber = "orderNumber";
            public readonly string type = "type";
            public readonly string replyToId = "replyToId";
        }
        static readonly ActionParamsClass_ReplyTo s_params_ReplyTo = new ActionParamsClass_ReplyTo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReplyTo ReplyToParams { get { return s_params_ReplyTo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReplyTo
        {
            public readonly string replyToId = "replyToId";
            public readonly string orderNumber = "orderNumber";
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_ComposeEmail s_params_ComposeEmail = new ActionParamsClass_ComposeEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ComposeEmail ComposeEmailParams { get { return s_params_ComposeEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ComposeEmail
        {
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_SetNoResponseNeeded s_params_SetNoResponseNeeded = new ActionParamsClass_SetNoResponseNeeded();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetNoResponseNeeded SetNoResponseNeededParams { get { return s_params_SetNoResponseNeeded; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetNoResponseNeeded
        {
            public readonly string emailId = "emailId";
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_DismissResponsePromised s_params_DismissResponsePromised = new ActionParamsClass_DismissResponsePromised();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DismissResponsePromised DismissResponsePromisedParams { get { return s_params_DismissResponsePromised; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DismissResponsePromised
        {
            public readonly string emailId = "emailId";
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_MarkAsReviewed s_params_MarkAsReviewed = new ActionParamsClass_MarkAsReviewed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MarkAsReviewed MarkAsReviewedParams { get { return s_params_MarkAsReviewed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MarkAsReviewed
        {
            public readonly string emailId = "emailId";
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_ViewEmail s_params_ViewEmail = new ActionParamsClass_ViewEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewEmail ViewEmailParams { get { return s_params_ViewEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewEmail
        {
            public readonly string id = "id";
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_GetAttachment s_params_GetAttachment = new ActionParamsClass_GetAttachment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAttachment GetAttachmentParams { get { return s_params_GetAttachment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAttachment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AssignEmailToOrder s_params_AssignEmailToOrder = new ActionParamsClass_AssignEmailToOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AssignEmailToOrder AssignEmailToOrderParams { get { return s_params_AssignEmailToOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AssignEmailToOrder
        {
            public readonly string emailId = "emailId";
            public readonly string orderNumber = "orderNumber";
        }
        static readonly ActionParamsClass_Escalate s_params_Escalate = new ActionParamsClass_Escalate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Escalate EscalateParams { get { return s_params_Escalate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Escalate
        {
            public readonly string emailId = "emailId";
            public readonly string orderNumber = "orderNumber";
            public readonly string escalated = "escalated";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AssignToOrder = "_AssignToOrder";
                public readonly string ComposeEmail = "ComposeEmail";
                public readonly string Index = "Index";
                public readonly string ViewEmail = "ViewEmail";
            }
            public readonly string _AssignToOrder = "~/Views/Email/_AssignToOrder.cshtml";
            public readonly string ComposeEmail = "~/Views/Email/ComposeEmail.cshtml";
            public readonly string Index = "~/Views/Email/Index.cshtml";
            public readonly string ViewEmail = "~/Views/Email/ViewEmail.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EmailController : Amazon.Web.Controllers.EmailController
    {
        public T4MVC_EmailController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(string orderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            IndexOverride(callInfo, orderId);
            return callInfo;
        }

        [NonAction]
        partial void GetAllEmailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.DateTime? dateFrom, System.DateTime? dateTo, string buyerName, string orderNumber, int? market, bool onlyIncoming, bool onlyWithoutAnswer, bool includeSystem, int? responseStatus);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllEmails(Kendo.Mvc.UI.DataSourceRequest request, System.DateTime? dateFrom, System.DateTime? dateTo, string buyerName, string orderNumber, int? market, bool onlyIncoming, bool onlyWithoutAnswer, bool includeSystem, int? responseStatus)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllEmails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateFrom", dateFrom);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dateTo", dateTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "buyerName", buyerName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "market", market);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "onlyIncoming", onlyIncoming);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "onlyWithoutAnswer", onlyWithoutAnswer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "includeSystem", includeSystem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "responseStatus", responseStatus);
            GetAllEmailsOverride(callInfo, request, dateFrom, dateTo, buyerName, orderNumber, market, onlyIncoming, onlyWithoutAnswer, includeSystem, responseStatus);
            return callInfo;
        }

        [NonAction]
        partial void UploadAttachmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> files);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadAttachment(Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> files)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "files", files);
            UploadAttachmentOverride(callInfo, request, files);
            return callInfo;
        }

        [NonAction]
        partial void AttachStyleImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string styleId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AttachStyleImage(string styleId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachStyleImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "styleId", styleId);
            AttachStyleImageOverride(callInfo, styleId);
            return callInfo;
        }

        [NonAction]
        partial void ValidateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Amazon.Web.ViewModels.Emails.ComposeEmailViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Validate(Amazon.Web.ViewModels.Emails.ComposeEmailViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Validate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ValidateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SendEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Amazon.Web.ViewModels.Emails.ComposeEmailViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendEmail(Amazon.Web.ViewModels.Emails.ComposeEmailViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SendEmailOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void TestEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TestEmail()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TestEmail);
            TestEmailOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ComposeEmailFromTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orderNumber, Amazon.Core.Models.EmailTypes type, long? replyToId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ComposeEmailFromTemplate(string orderNumber, Amazon.Core.Models.EmailTypes type, long? replyToId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComposeEmailFromTemplate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyToId", replyToId);
            ComposeEmailFromTemplateOverride(callInfo, orderNumber, type, replyToId);
            return callInfo;
        }

        [NonAction]
        partial void GetTemplateInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orderNumber, Amazon.Core.Models.EmailTypes type, long? replyToId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetTemplateInfo(string orderNumber, Amazon.Core.Models.EmailTypes type, long? replyToId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetTemplateInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyToId", replyToId);
            GetTemplateInfoOverride(callInfo, orderNumber, type, replyToId);
            return callInfo;
        }

        [NonAction]
        partial void ReplyToOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long replyToId, string orderNumber, Amazon.Core.Models.EmailTypes? type);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReplyTo(long replyToId, string orderNumber, Amazon.Core.Models.EmailTypes? type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReplyTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyToId", replyToId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ReplyToOverride(callInfo, replyToId, orderNumber, type);
            return callInfo;
        }

        [NonAction]
        partial void ComposeEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult ComposeEmail(string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComposeEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ComposeEmailOverride(callInfo, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void SetNoResponseNeededOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long emailId, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetNoResponseNeeded(long emailId, string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetNoResponseNeeded);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailId", emailId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            SetNoResponseNeededOverride(callInfo, emailId, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void DismissResponsePromisedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long emailId, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult DismissResponsePromised(long emailId, string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DismissResponsePromised);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailId", emailId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            DismissResponsePromisedOverride(callInfo, emailId, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void MarkAsReviewedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long emailId, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult MarkAsReviewed(long emailId, string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkAsReviewed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailId", emailId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            MarkAsReviewedOverride(callInfo, emailId, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void ViewEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewEmail(long id, string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ViewEmailOverride(callInfo, id, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void GetAttachmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAttachment(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAttachment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetAttachmentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AssignEmailToOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long emailId, string orderNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult AssignEmailToOrder(long emailId, string orderNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssignEmailToOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailId", emailId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            AssignEmailToOrderOverride(callInfo, emailId, orderNumber);
            return callInfo;
        }

        [NonAction]
        partial void EscalateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long emailId, string orderNumber, bool escalated);

        [NonAction]
        public override System.Web.Mvc.ActionResult Escalate(long emailId, string orderNumber, bool escalated)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Escalate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailId", emailId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderNumber", orderNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "escalated", escalated);
            EscalateOverride(callInfo, emailId, orderNumber, escalated);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
