// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Amazon.Web.Controllers
{
    public partial class ImageController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ImageController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ImageController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllMarketImages()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllMarketImages);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllStyleImages()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllStyleImages);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReplaceStyleImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReplaceStyleImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetItemLargeImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemLargeImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetItemLargeIncludeParentImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemLargeIncludeParentImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetItemImageDiff()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemImageDiff);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ToggleIgnoreItemImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToggleIgnoreItemImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Thumbnail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Thumbnail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetUploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetUploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Swatch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Swatch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Walmart()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Walmart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Jet()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Jet);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult eBay()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.eBay);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Groupon()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Groupon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Raw()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Raw);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Get()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Save()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveWithCheck()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveWithCheck);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveSingle()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSingle);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Remove()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Remove);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ImageController Actions { get { return MVC.Image; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Image";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Image";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string MarketImages = "MarketImages";
            public readonly string StyleImages = "StyleImages";
            public readonly string GetAllMarketImages = "GetAllMarketImages";
            public readonly string GetAllStyleImages = "GetAllStyleImages";
            public readonly string ReplaceStyleImage = "ReplaceStyleImage";
            public readonly string ResetItemLargeImage = "ResetItemLargeImage";
            public readonly string ResetItemLargeIncludeParentImage = "ResetItemLargeIncludeParentImage";
            public readonly string ResetItemImageDiff = "ResetItemImageDiff";
            public readonly string ToggleIgnoreItemImage = "ToggleIgnoreItemImage";
            public readonly string Thumbnail = "Thumbnail";
            public readonly string GetUploadImage = "GetUploadImage";
            public readonly string Swatch = "Swatch";
            public readonly string Walmart = "Walmart";
            public readonly string Jet = "Jet";
            public readonly string eBay = "eBay";
            public readonly string Groupon = "Groupon";
            public readonly string Raw = "Raw";
            public readonly string UploadImage = "UploadImage";
            public readonly string Get = "Get";
            public readonly string Save = "Save";
            public readonly string SaveWithCheck = "SaveWithCheck";
            public readonly string SaveSingle = "SaveSingle";
            public readonly string Remove = "Remove";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string MarketImages = "MarketImages";
            public const string StyleImages = "StyleImages";
            public const string GetAllMarketImages = "GetAllMarketImages";
            public const string GetAllStyleImages = "GetAllStyleImages";
            public const string ReplaceStyleImage = "ReplaceStyleImage";
            public const string ResetItemLargeImage = "ResetItemLargeImage";
            public const string ResetItemLargeIncludeParentImage = "ResetItemLargeIncludeParentImage";
            public const string ResetItemImageDiff = "ResetItemImageDiff";
            public const string ToggleIgnoreItemImage = "ToggleIgnoreItemImage";
            public const string Thumbnail = "Thumbnail";
            public const string GetUploadImage = "GetUploadImage";
            public const string Swatch = "Swatch";
            public const string Walmart = "Walmart";
            public const string Jet = "Jet";
            public const string eBay = "eBay";
            public const string Groupon = "Groupon";
            public const string Raw = "Raw";
            public const string UploadImage = "UploadImage";
            public const string Get = "Get";
            public const string Save = "Save";
            public const string SaveWithCheck = "SaveWithCheck";
            public const string SaveSingle = "SaveSingle";
            public const string Remove = "Remove";
        }


        static readonly ActionParamsClass_GetAllMarketImages s_params_GetAllMarketImages = new ActionParamsClass_GetAllMarketImages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllMarketImages GetAllMarketImagesParams { get { return s_params_GetAllMarketImages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllMarketImages
        {
            public readonly string request = "request";
            public readonly string market = "market";
            public readonly string marketplaceId = "marketplaceId";
            public readonly string keywords = "keywords";
            public readonly string onlyIgnored = "onlyIgnored";
        }
        static readonly ActionParamsClass_GetAllStyleImages s_params_GetAllStyleImages = new ActionParamsClass_GetAllStyleImages();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllStyleImages GetAllStyleImagesParams { get { return s_params_GetAllStyleImages; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllStyleImages
        {
            public readonly string request = "request";
            public readonly string keywords = "keywords";
            public readonly string styleWithLoRes = "styleWithLoRes";
            public readonly string withMarketHiRes = "withMarketHiRes";
        }
        static readonly ActionParamsClass_ReplaceStyleImage s_params_ReplaceStyleImage = new ActionParamsClass_ReplaceStyleImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReplaceStyleImage ReplaceStyleImageParams { get { return s_params_ReplaceStyleImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReplaceStyleImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ResetItemLargeImage s_params_ResetItemLargeImage = new ActionParamsClass_ResetItemLargeImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetItemLargeImage ResetItemLargeImageParams { get { return s_params_ResetItemLargeImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetItemLargeImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ResetItemLargeIncludeParentImage s_params_ResetItemLargeIncludeParentImage = new ActionParamsClass_ResetItemLargeIncludeParentImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetItemLargeIncludeParentImage ResetItemLargeIncludeParentImageParams { get { return s_params_ResetItemLargeIncludeParentImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetItemLargeIncludeParentImage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ResetItemImageDiff s_params_ResetItemImageDiff = new ActionParamsClass_ResetItemImageDiff();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetItemImageDiff ResetItemImageDiffParams { get { return s_params_ResetItemImageDiff; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetItemImageDiff
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ToggleIgnoreItemImage s_params_ToggleIgnoreItemImage = new ActionParamsClass_ToggleIgnoreItemImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ToggleIgnoreItemImage ToggleIgnoreItemImageParams { get { return s_params_ToggleIgnoreItemImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ToggleIgnoreItemImage
        {
            public readonly string id = "id";
            public readonly string isIgnored = "isIgnored";
        }
        static readonly ActionParamsClass_Thumbnail s_params_Thumbnail = new ActionParamsClass_Thumbnail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Thumbnail ThumbnailParams { get { return s_params_Thumbnail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Thumbnail
        {
            public readonly string path = "path";
            public readonly string width = "width";
            public readonly string height = "height";
            public readonly string rotate = "rotate";
        }
        static readonly ActionParamsClass_GetUploadImage s_params_GetUploadImage = new ActionParamsClass_GetUploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetUploadImage GetUploadImageParams { get { return s_params_GetUploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetUploadImage
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Swatch s_params_Swatch = new ActionParamsClass_Swatch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Swatch SwatchParams { get { return s_params_Swatch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Swatch
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Walmart s_params_Walmart = new ActionParamsClass_Walmart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Walmart WalmartParams { get { return s_params_Walmart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Walmart
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Jet s_params_Jet = new ActionParamsClass_Jet();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Jet JetParams { get { return s_params_Jet; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Jet
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_eBay s_params_eBay = new ActionParamsClass_eBay();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_eBay eBayParams { get { return s_params_eBay; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_eBay
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Groupon s_params_Groupon = new ActionParamsClass_Groupon();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Groupon GrouponParams { get { return s_params_Groupon; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Groupon
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Raw s_params_Raw = new ActionParamsClass_Raw();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Raw RawParams { get { return s_params_Raw; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Raw
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_UploadImage s_params_UploadImage = new ActionParamsClass_UploadImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadImage UploadImageParams { get { return s_params_UploadImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadImage
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Get s_params_Get = new ActionParamsClass_Get();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get GetParams { get { return s_params_Get; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get
        {
            public readonly string filename = "filename";
        }
        static readonly ActionParamsClass_Save s_params_Save = new ActionParamsClass_Save();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Save SaveParams { get { return s_params_Save; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Save
        {
            public readonly string image1 = "image1";
            public readonly string image2 = "image2";
            public readonly string image3 = "image3";
            public readonly string image4 = "image4";
            public readonly string image5 = "image5";
            public readonly string image6 = "image6";
            public readonly string image7 = "image7";
            public readonly string image8 = "image8";
            public readonly string image9 = "image9";
            public readonly string image10 = "image10";
            public readonly string image11 = "image11";
            public readonly string image12 = "image12";
        }
        static readonly ActionParamsClass_SaveWithCheck s_params_SaveWithCheck = new ActionParamsClass_SaveWithCheck();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveWithCheck SaveWithCheckParams { get { return s_params_SaveWithCheck; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveWithCheck
        {
            public readonly string image1 = "image1";
            public readonly string image2 = "image2";
            public readonly string image3 = "image3";
            public readonly string image4 = "image4";
            public readonly string image5 = "image5";
            public readonly string image6 = "image6";
            public readonly string image7 = "image7";
            public readonly string image8 = "image8";
            public readonly string image9 = "image9";
            public readonly string image10 = "image10";
            public readonly string image11 = "image11";
            public readonly string image12 = "image12";
        }
        static readonly ActionParamsClass_SaveSingle s_params_SaveSingle = new ActionParamsClass_SaveSingle();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSingle SaveSingleParams { get { return s_params_SaveSingle; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSingle
        {
            public readonly string request = "request";
            public readonly string files = "files";
        }
        static readonly ActionParamsClass_Remove s_params_Remove = new ActionParamsClass_Remove();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Remove RemoveParams { get { return s_params_Remove; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Remove
        {
            public readonly string fileNames = "fileNames";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string MarketImages = "MarketImages";
                public readonly string StyleImages = "StyleImages";
            }
            public readonly string Index = "~/Views/Image/Index.cshtml";
            public readonly string MarketImages = "~/Views/Image/MarketImages.cshtml";
            public readonly string StyleImages = "~/Views/Image/StyleImages.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ImageController : Amazon.Web.Controllers.ImageController
    {
        public T4MVC_ImageController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MarketImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MarketImages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarketImages);
            MarketImagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StyleImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult StyleImages()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StyleImages);
            StyleImagesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllMarketImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, int? market, string marketplaceId, string keywords, bool onlyIgnored);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllMarketImages(Kendo.Mvc.UI.DataSourceRequest request, int? market, string marketplaceId, string keywords, bool onlyIgnored)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllMarketImages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "market", market);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "marketplaceId", marketplaceId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywords", keywords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "onlyIgnored", onlyIgnored);
            GetAllMarketImagesOverride(callInfo, request, market, marketplaceId, keywords, onlyIgnored);
            return callInfo;
        }

        [NonAction]
        partial void GetAllStyleImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, string keywords, bool styleWithLoRes, bool withMarketHiRes);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllStyleImages(Kendo.Mvc.UI.DataSourceRequest request, string keywords, bool styleWithLoRes, bool withMarketHiRes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllStyleImages);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywords", keywords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "styleWithLoRes", styleWithLoRes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "withMarketHiRes", withMarketHiRes);
            GetAllStyleImagesOverride(callInfo, request, keywords, styleWithLoRes, withMarketHiRes);
            return callInfo;
        }

        [NonAction]
        partial void ReplaceStyleImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReplaceStyleImage(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReplaceStyleImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ReplaceStyleImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ResetItemLargeImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetItemLargeImage(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemLargeImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ResetItemLargeImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ResetItemLargeIncludeParentImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetItemLargeIncludeParentImage(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemLargeIncludeParentImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ResetItemLargeIncludeParentImageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ResetItemImageDiffOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetItemImageDiff(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetItemImageDiff);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ResetItemImageDiffOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ToggleIgnoreItemImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id, bool isIgnored);

        [NonAction]
        public override System.Web.Mvc.ActionResult ToggleIgnoreItemImage(long id, bool isIgnored)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToggleIgnoreItemImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isIgnored", isIgnored);
            ToggleIgnoreItemImageOverride(callInfo, id, isIgnored);
            return callInfo;
        }

        [NonAction]
        partial void ThumbnailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string path, int width, int height, string rotate);

        [NonAction]
        public override System.Web.Mvc.ActionResult Thumbnail(string path, int width, int height, string rotate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Thumbnail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "path", path);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "width", width);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "height", height);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rotate", rotate);
            ThumbnailOverride(callInfo, path, width, height, rotate);
            return callInfo;
        }

        [NonAction]
        partial void GetUploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetUploadImage(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetUploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            GetUploadImageOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void SwatchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Swatch(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Swatch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            SwatchOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void WalmartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Walmart(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Walmart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            WalmartOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void JetOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Jet(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Jet);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            JetOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void eBayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult eBay(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.eBay);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            eBayOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void GrouponOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Groupon(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Groupon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            GrouponOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void RawOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Raw(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Raw);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            RawOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void UploadImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadImage(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            UploadImageOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void GetOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string filename);

        [NonAction]
        public override System.Web.Mvc.ActionResult Get(string filename)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filename", filename);
            GetOverride(callInfo, filename);
            return callInfo;
        }

        [NonAction]
        partial void SaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image1, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image2, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image3, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image4, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image5, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image6, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image7, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image8, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image9, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image10, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image11, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image12);

        [NonAction]
        public override System.Web.Mvc.ActionResult Save(System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image1, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image2, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image3, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image4, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image5, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image6, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image7, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image8, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image9, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image10, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image11, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image12)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Save);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image1", image1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image2", image2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image3", image3);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image4", image4);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image5", image5);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image6", image6);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image7", image7);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image8", image8);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image9", image9);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image10", image10);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image11", image11);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image12", image12);
            SaveOverride(callInfo, image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12);
            return callInfo;
        }

        [NonAction]
        partial void SaveWithCheckOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image1, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image2, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image3, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image4, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image5, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image6, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image7, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image8, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image9, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image10, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image11, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image12);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveWithCheck(System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image1, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image2, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image3, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image4, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image5, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image6, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image7, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image8, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image9, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image10, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image11, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> image12)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveWithCheck);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image1", image1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image2", image2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image3", image3);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image4", image4);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image5", image5);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image6", image6);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image7", image7);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image8", image8);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image9", image9);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image10", image10);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image11", image11);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "image12", image12);
            SaveWithCheckOverride(callInfo, image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12);
            return callInfo;
        }

        [NonAction]
        partial void SaveSingleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> files);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveSingle(Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<System.Web.HttpPostedFileBase> files)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSingle);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "files", files);
            SaveSingleOverride(callInfo, request, files);
            return callInfo;
        }

        [NonAction]
        partial void RemoveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string[] fileNames);

        [NonAction]
        public override System.Web.Mvc.ActionResult Remove(string[] fileNames)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Remove);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileNames", fileNames);
            RemoveOverride(callInfo, fileNames);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
