// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Amazon.Web.Controllers
{
    public partial class MarketBarcodeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MarketBarcodeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MarketBarcodeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RequestBarcode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RequestBarcode);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MarketBarcodeController Actions { get { return MVC.MarketBarcode; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "MarketBarcode";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "MarketBarcode";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string OnRequestBarcode = "OnRequestBarcode";
            public readonly string RequestBarcode = "RequestBarcode";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string OnRequestBarcode = "OnRequestBarcode";
            public const string RequestBarcode = "RequestBarcode";
        }


        static readonly ActionParamsClass_RequestBarcode s_params_RequestBarcode = new ActionParamsClass_RequestBarcode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RequestBarcode RequestBarcodeParams { get { return s_params_RequestBarcode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RequestBarcode
        {
            public readonly string productUrl = "productUrl";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string RequestBarcodePopupContent = "RequestBarcodePopupContent";
            }
            public readonly string RequestBarcodePopupContent = "~/Views/MarketBarcode/RequestBarcodePopupContent.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MarketBarcodeController : Amazon.Web.Controllers.MarketBarcodeController
    {
        public T4MVC_MarketBarcodeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void OnRequestBarcodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult OnRequestBarcode()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OnRequestBarcode);
            OnRequestBarcodeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RequestBarcodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string productUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult RequestBarcode(string productUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RequestBarcode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productUrl", productUrl);
            RequestBarcodeOverride(callInfo, productUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
