// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Amazon.Web.Controllers
{
    public partial class SalesExtReportController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SalesExtReportController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SalesExtReportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAll()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAll);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SalesExtReportController Actions { get { return MVC.SalesExtReport; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SalesExtReport";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SalesExtReport";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetAll = "GetAll";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetAll = "GetAll";
        }


        static readonly ActionParamsClass_GetAll s_params_GetAll = new ActionParamsClass_GetAll();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAll GetAllParams { get { return s_params_GetAll; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAll
        {
            public readonly string request = "request";
            public readonly string fromDate = "fromDate";
            public readonly string toDate = "toDate";
            public readonly string keywords = "keywords";
            public readonly string gender = "gender";
            public readonly string itemStyles = "itemStyles[]";
            public readonly string mainLicense = "mainLicense";
            public readonly string subLicense = "subLicense";
            public readonly string market = "market";
            public readonly string marketplaceId = "marketplaceId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/SalesExtReport/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SalesExtReportController : Amazon.Web.Controllers.SalesExtReportController
    {
        public T4MVC_SalesExtReportController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Amazon.Web.ViewModels.Grid.GridRequest request, System.DateTime? fromDate, System.DateTime? toDate, string keywords, string gender, System.Collections.Generic.List<int> itemStyles, int? mainLicense, int? subLicense, int? market, string marketplaceId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAll(Amazon.Web.ViewModels.Grid.GridRequest request, System.DateTime? fromDate, System.DateTime? toDate, string keywords, string gender, System.Collections.Generic.List<int> itemStyles, int? mainLicense, int? subLicense, int? market, string marketplaceId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAll);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fromDate", fromDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toDate", toDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywords", keywords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gender", gender);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemStyles[]", itemStyles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mainLicense", mainLicense);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "subLicense", subLicense);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "market", market);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "marketplaceId", marketplaceId);
            GetAllOverride(callInfo, request, fromDate, toDate, keywords, gender, itemStyles, mainLicense, subLicense, market, marketplaceId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
