// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DhlCloseoutPartial = "_DhlCloseoutPartial";
                public readonly string _FedexCloseoutPartial = "_FedexCloseoutPartial";
                public readonly string _HeaderSearchPartial = "_HeaderSearchPartial";
                public readonly string _IbcCloseoutPartial = "_IbcCloseoutPartial";
                public readonly string _ItemFeatures = "_ItemFeatures";
                public readonly string _ItemImages = "_ItemImages";
                public readonly string _ItemLocations = "_ItemLocations";
                public readonly string _ItemPublishes = "_ItemPublishes";
                public readonly string _ItemStyleItems = "_ItemStyleItems";
                public readonly string _Layout = "_Layout";
                public readonly string _LayoutLight = "_LayoutLight";
                public readonly string _LayoutMobile = "_LayoutMobile";
                public readonly string _LogOnPartial = "_LogOnPartial";
                public readonly string _Menu = "_Menu";
                public readonly string _NotificationPartial = "_NotificationPartial";
                public readonly string _OrderHistory = "_OrderHistory";
                public readonly string _OrderMessageSummary = "_OrderMessageSummary";
                public readonly string _OrderSummary = "_OrderSummary";
                public readonly string _PrintLayout = "_PrintLayout";
                public readonly string _SetBulkShipping = "_SetBulkShipping";
                public readonly string _StyleHistory = "_StyleHistory";
                public readonly string _SyncStatusPartial = "_SyncStatusPartial";
                public readonly string _TemplateFastGrid = "_TemplateFastGrid";
                public readonly string _TemplateGridPager = "_TemplateGridPager";
                public readonly string _TemplatesOrder = "_TemplatesOrder";
                public readonly string _TemplatesProduct = "_TemplatesProduct";
                public readonly string _TemplatesStyle = "_TemplatesStyle";
                public readonly string _TermsAndConditionsPopup = "_TermsAndConditionsPopup";
                public readonly string Edit = "Edit";
                public readonly string EditEmpty = "EditEmpty";
                public readonly string EditNew = "EditNew";
                public readonly string Error = "Error";
                public readonly string Message = "Message";
            }
            public readonly string _DhlCloseoutPartial = "~/Views/Shared/_DhlCloseoutPartial.cshtml";
            public readonly string _FedexCloseoutPartial = "~/Views/Shared/_FedexCloseoutPartial.cshtml";
            public readonly string _HeaderSearchPartial = "~/Views/Shared/_HeaderSearchPartial.cshtml";
            public readonly string _IbcCloseoutPartial = "~/Views/Shared/_IbcCloseoutPartial.cshtml";
            public readonly string _ItemFeatures = "~/Views/Shared/_ItemFeatures.cshtml";
            public readonly string _ItemImages = "~/Views/Shared/_ItemImages.cshtml";
            public readonly string _ItemLocations = "~/Views/Shared/_ItemLocations.cshtml";
            public readonly string _ItemPublishes = "~/Views/Shared/_ItemPublishes.cshtml";
            public readonly string _ItemStyleItems = "~/Views/Shared/_ItemStyleItems.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LayoutLight = "~/Views/Shared/_LayoutLight.cshtml";
            public readonly string _LayoutMobile = "~/Views/Shared/_LayoutMobile.cshtml";
            public readonly string _LogOnPartial = "~/Views/Shared/_LogOnPartial.cshtml";
            public readonly string _Menu = "~/Views/Shared/_Menu.cshtml";
            public readonly string _NotificationPartial = "~/Views/Shared/_NotificationPartial.cshtml";
            public readonly string _OrderHistory = "~/Views/Shared/_OrderHistory.cshtml";
            public readonly string _OrderMessageSummary = "~/Views/Shared/_OrderMessageSummary.cshtml";
            public readonly string _OrderSummary = "~/Views/Shared/_OrderSummary.cshtml";
            public readonly string _PrintLayout = "~/Views/Shared/_PrintLayout.cshtml";
            public readonly string _SetBulkShipping = "~/Views/Shared/_SetBulkShipping.cshtml";
            public readonly string _StyleHistory = "~/Views/Shared/_StyleHistory.cshtml";
            public readonly string _SyncStatusPartial = "~/Views/Shared/_SyncStatusPartial.cshtml";
            public readonly string _TemplateFastGrid = "~/Views/Shared/_TemplateFastGrid.cshtml";
            public readonly string _TemplateGridPager = "~/Views/Shared/_TemplateGridPager.cshtml";
            public readonly string _TemplatesOrder = "~/Views/Shared/_TemplatesOrder.cshtml";
            public readonly string _TemplatesProduct = "~/Views/Shared/_TemplatesProduct.cshtml";
            public readonly string _TemplatesStyle = "~/Views/Shared/_TemplatesStyle.cshtml";
            public readonly string _TermsAndConditionsPopup = "~/Views/Shared/_TermsAndConditionsPopup.cshtml";
            public readonly string Edit = "~/Views/Shared/Edit.cshtml";
            public readonly string EditEmpty = "~/Views/Shared/EditEmpty.cshtml";
            public readonly string EditNew = "~/Views/Shared/EditNew.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Message = "~/Views/Shared/Message.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Country = "Country";
                public readonly string ItemType = "ItemType";
                public readonly string ItemTypeMultiSelect = "ItemTypeMultiSelect";
                public readonly string UserViewModel = "UserViewModel";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
